//! Phase 1B credential-leaf compatibility vectors.
//!
//! These tests read `tests/fixtures/phase1b-eligibility-v2.json`, which is
//! generated by `scripts/generate-phase1b-fixture.js` from the JavaScript
//! schema the Circom eligibility circuit mirrors. Asserting the Rust leaf
//! against that file is what keeps the Rust, JavaScript, and Circom credential
//! leaves from drifting apart.
//!
//! The expected values are authoritative: if Rust disagrees, Rust is wrong.

#![allow(clippy::unwrap_used)]

use serde_json::Value;
use zwa_commitments::{receiver_commitment, trade_commitment_v1};
use zwa_credentials::{
    ActiveCredential, CredentialAuthorityCommitment, CredentialExpiry, CredentialLeaf,
    CredentialMeta, CredentialNonce, InvestorClass, Jurisdiction,
};
use zwa_protocol::{
    AssetBaseBytes, MatcherFee, OrchardReceiverBytes, PolicyRoot, RecipientCommitment,
    SubjectSecret, TradeAmount, TradeExpiry, TradeIntent, TradeNonce, ZatoshiAmount,
};

/// Mandatory Phase 0G golden `TradeCommitmentV1`, unchanged by Phase 1B.
const PHASE_0G_GOLDEN_TRADE_COMMITMENT: &str =
    "10187400613857124614980227259922066295752635539032972479692659299555113110306";

fn fixture() -> Value {
    let raw = include_str!("../../../tests/fixtures/phase1b-eligibility-v2.json");
    serde_json::from_str(raw).unwrap()
}

fn text(node: &Value, key: &str) -> String {
    node[key]
        .as_str()
        .unwrap_or_else(|| panic!("fixture field {key} must be a string"))
        .to_owned()
}

/// Builds the approved credential exactly as the fixture records it.
fn approved_credential(fx: &Value, receiver_key: &str) -> ActiveCredential {
    let credential = &fx["credential"];
    ActiveCredential {
        authority_commitment: CredentialAuthorityCommitment::from_decimal_str(&text(
            credential,
            "credentialAuthorityCommitment",
        ))
        .unwrap(),
        subject_secret: SubjectSecret::from_decimal_str(&text(credential, "subjectSecret"))
            .unwrap(),
        investor_class: InvestorClass::from_u64(text(credential, "investorClass").parse().unwrap())
            .unwrap(),
        jurisdiction: Jurisdiction::from_u64(text(credential, "jurisdiction").parse().unwrap())
            .unwrap(),
        credential_expiry: CredentialExpiry::new(
            text(credential, "credentialExpiry").parse().unwrap(),
        ),
        nonce: CredentialNonce::new(text(credential, "credentialNonce").parse().unwrap()),
        approved_receiver: OrchardReceiverBytes::from_hex(&text(&fx["receiver"], receiver_key))
            .unwrap(),
    }
}

#[test]
fn rust_reproduces_the_phase1b_credential_leaf() {
    let fx = fixture();
    let credential = approved_credential(&fx, "approvedBytes");
    let expected = &fx["credential"];

    assert_eq!(
        credential.meta(),
        CredentialMeta::from_decimal_str(&text(expected, "credentialMeta")).unwrap()
    );
    assert_eq!(
        credential.leaf(),
        CredentialLeaf::from_decimal_str(&text(expected, "credentialLeaf")).unwrap()
    );
}

#[test]
fn the_approved_receiver_commitment_is_the_canonical_receiver_commitment() {
    // Phase 1B reuses the frozen receiver encoding rather than inventing a
    // second one, so the leaf's approved receiver commitment must equal the
    // canonical commitment over the same raw 43 bytes.
    let fx = fixture();
    let credential = approved_credential(&fx, "approvedBytes");
    let receiver = OrchardReceiverBytes::from_hex(&text(&fx["receiver"], "approvedBytes")).unwrap();

    assert_eq!(
        credential.approved_receiver_commitment(),
        receiver_commitment(&receiver)
    );
    assert_eq!(
        credential.approved_receiver_commitment().to_string(),
        text(&fx["credential"], "approvedReceiverCommitment")
    );
    // The same value the recipient binding consumes.
    assert_eq!(
        credential.approved_receiver_commitment().to_string(),
        text(&fx["recipientBinding"]["approved"], "receiverCommitment")
    );
}

#[test]
fn a_substituted_receiver_produces_a_different_credential_leaf() {
    // The decisive Phase 1B property expressed at the leaf: the authority
    // approved receiver A, so a leaf built for receiver B cannot be the leaf
    // that the active credential root commits to.
    let fx = fixture();
    let approved = approved_credential(&fx, "approvedBytes");
    let substituted = approved_credential(&fx, "substituteBytes");

    assert_eq!(approved.meta(), substituted.meta());
    assert_ne!(approved.leaf(), substituted.leaf());
    assert_eq!(
        substituted.leaf(),
        CredentialLeaf::from_decimal_str(&text(
            &fx["credentialApprovingSubstitute"],
            "credentialLeaf"
        ))
        .unwrap()
    );
    assert!(!approved.authorizes(&substituted.approved_receiver));
}

#[test]
fn phase1b_does_not_change_the_frozen_phase0g_trade_commitment() {
    // Phase 1B changes the credential leaf only. The trade the fixture records
    // must still hash to the frozen Phase 0G golden value.
    let fx = fixture();
    let trade = &fx["trade"];
    let intent = TradeIntent {
        offered_asset: AssetBaseBytes::from_hex(&text(trade, "offeredAssetBase")).unwrap(),
        offered_amount: TradeAmount::new(text(trade, "offeredAmount").parse().unwrap()),
        requested_asset: AssetBaseBytes::from_hex(&text(trade, "requestedAssetBase")).unwrap(),
        requested_amount: TradeAmount::new(text(trade, "requestedAmount").parse().unwrap()),
        recipient_commitment: RecipientCommitment::from_decimal_str(&text(
            trade,
            "recipientCommitment",
        ))
        .unwrap(),
        policy_root: PolicyRoot::from_decimal_str(&text(trade, "policyRoot")).unwrap(),
        matcher_fee: MatcherFee::new(
            ZatoshiAmount::new(text(trade, "matcherFeeAmount").parse().unwrap()),
            RecipientCommitment::from_decimal_str(&text(trade, "matcherFeeRecipientCommitment"))
                .unwrap(),
        ),
        nonce: TradeNonce::new(text(trade, "nonce").parse().unwrap()),
        expiry: TradeExpiry::new(text(trade, "expiry").parse().unwrap()),
    };

    assert_eq!(
        trade_commitment_v1(&intent).to_string(),
        PHASE_0G_GOLDEN_TRADE_COMMITMENT
    );
    assert_eq!(
        text(trade, "tradeCommitment"),
        PHASE_0G_GOLDEN_TRADE_COMMITMENT
    );
}

#[test]
fn the_substituted_receiver_changes_the_trade_commitment_too() {
    // Receiver substitution is visible in the trade commitment as well, so the
    // attacker in `substitutedReceiverInput` must present a different public
    // trade commitment; the credential leaf is what actually stops them.
    let fx = fixture();
    assert_ne!(
        text(&fx["tradeWithSubstituteReceiver"], "tradeCommitment"),
        PHASE_0G_GOLDEN_TRADE_COMMITMENT
    );
    assert_ne!(
        text(&fx["recipientBinding"]["approved"], "recipientCommitment"),
        text(&fx["recipientBinding"]["substitute"], "recipientCommitment")
    );
}

#[test]
fn the_adversarial_circuit_inputs_disagree_with_the_active_credential_root() {
    // Every negative vector must present a credential witness whose recomputed
    // leaf cannot sit under the root it claims. This pins the fixture so a
    // stale or accidentally-fixed negative vector cannot pass silently.
    let fx = fixture();
    let approved_root = text(&fx["credential"], "activeCredentialRoot");
    let substitute_root = text(&fx["credentialApprovingSubstitute"], "activeCredentialRoot");
    assert_ne!(approved_root, substitute_root);

    // A and D claim the approved root; C claims the substitute root.
    assert_eq!(
        text(&fx["approvedReceiverInput"], "activeCredentialRoot"),
        approved_root
    );
    assert_eq!(
        text(&fx["substitutedReceiverInput"], "activeCredentialRoot"),
        approved_root
    );
    assert_eq!(
        text(&fx["mutatedTradeRecipientInput"], "activeCredentialRoot"),
        approved_root
    );
    assert_eq!(
        text(&fx["mutatedApprovedReceiverInput"], "activeCredentialRoot"),
        substitute_root
    );

    // The negative vectors really do carry the substitute receiver limbs.
    let substitute_limb0 = text(&fx["receiver"]["substituteLimbs"], "limb0");
    assert_eq!(
        text(&fx["substitutedReceiverInput"], "receiverLimb0"),
        substitute_limb0
    );
    assert_eq!(
        text(&fx["mutatedTradeRecipientInput"], "receiverLimb0"),
        substitute_limb0
    );
    assert_eq!(
        text(&fx["approvedReceiverInput"], "receiverLimb0"),
        text(&fx["receiver"]["approvedLimbs"], "limb0")
    );
}
